### ISSUE TITLE
More config options for the user

### ISSUE THREAD

**Issue by zoenglinghou** [robertoszek/pleroma-twitter-info-grabber#2]
It would be nice to have options for the scope and sensitivity of the statuses for a user. I could implement this in a PR if you like.

ps. I am also happy to help with other issues & TODOs

**Comment by robertoszek** [comment]
I appreciate the help @zoenglinghou !
I've added the scope and sensitivity option to be set on a user per user basis or globally on the config file:
[Allow visibility and sensitivity to be set in the config file](https://github.com/robertoszek/pleroma-twitter-info-grabber/commit/37164f0cb1a5c496642cee9413c650a032edda42)
And has been merged into master: #5 

If you're up to it I was thinking of also adding support for polls. I'll create the issue and if you feel like you can work on it.

**Comment by zoenglinghou** [comment]
I would study the poll APIs a bit and see if I can implement it over the weekend.

**Comment by robertoszek** [comment]
Sounds great!
Closing this issue as resolved 😉️
