### ISSUE TITLE
Getting Error in get_date_last_pleroma_post

### ISSUE THREAD

**Issue by jimmybrancaccio** [robertoszek/pleroma-twitter-info-grabber#21]
Greetings!

I was able to run this once and it worked wonderfully, but then it started to fail with:

```
pleroma_bot - ERROR - Exception occurred
Traceback (most recent call last):
  File "/home/jimmy/.local/lib/python3.8/site-packages/pleroma_bot/cli.py", line 185, in main
    date_pleroma = user.get_date_last_pleroma_post()
  File "/home/jimmy/.local/lib/python3.8/site-packages/pleroma_bot/_pleroma.py", line 41, in get_date_last_pleroma_post
    datetime.strptime(
  File "/usr/lib/python3.8/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/lib/python3.8/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2021-01-07T16:47:58.915Z' does not match format '%Y-%m-%dT%H:%M:%S.000Z'
```

However, unless if it's not obvious those do match. `2021-01-07T16:47:58.915Z` uses the format `%Y-%m-%dT%H:%M:%S.000Z`.

Any ideas? I really hope it's not something obvious, I'm going to feel so stupid haha 😝

**Comment by jimmybrancaccio** [comment]
I think I may have figured it out. https://github.com/robertoszek/pleroma-twitter-info-grabber/blob/28c1c7df57d8a37f8f361cb8639e9bad5a41bc9e/pleroma_bot/_pleroma.py#L41 I've changed to:

```python
posts[0]["created_at"], "%Y-%m-%dT%H:%M:%S.%fZ"
```

This may or may not be correct, I'm not a great developer and definitely not with Python haha.

**Comment by robertoszek** [comment]
Hi Jimmy,
you're indeed correct! 
Actually, this was corrected on the develop branch back in November, but hasn't been promoted to the master branch yet. (commit [1c00329](https://github.com/robertoszek/pleroma-twitter-info-grabber/commit/b687b6ff9fd432edb222676194c00c1f2988a7d7#diff-9ce5527dcb9f775c908466be0aae0cc55972b34a1447bca1fbafdcf39bf20392))

Good work figuring it out! I did the same format change as you proposed.

**Comment by jimmybrancaccio** [comment]
Oh, cool! Go me haha. Glad to know it was fixed though! Hopefully it makes it way to master soon - so others can benefit haha I think we can consider this one closed then!

**Comment by robertoszek** [comment]
Absolutely, I was considering doing a push pretty soon, I always wait for some substantial changes to accumulate before promoting them (unless something is completely broken and needs a hotfix ASAP 😅)

You can always check what it's currently waiting to be promoted by looking at the changelog in the develop branch: 
https://github.com/robertoszek/pleroma-twitter-info-grabber/blob/develop/CHANGELOG.md#unreleased

And if you're feeling adventurous you can even install test releases by running:
```console
pip install --index-url https://test.pypi.org/simple/ pleroma-bot
```

But considering you ran into this edge case, I'm going to merge the develop into master as soon as I'm able.
Thanks again for bringing it to my attention!

**Comment by jimmybrancaccio** [comment]
@robertoszek Sounds fair 😄 

I think I found another issue which doesn't seem to be in the unreleased list, I can create a new issue for it if you'd like. Briefly though, for some reason, it's having trouble fetching Twitter profile banners and of course it's only sometimes. It seems that appending `/1500x500` to the URL always allows it to fetch properly. For example:

```
$ curl -I https://pbs.twimg.com/profile_banners/16348722/1355568199
HTTP/2 404 
accept-ranges: bytes
access-control-allow-origin: *
access-control-expose-headers: Content-Length
age: 224
cache-control: max-age=300, must-revalidate
date: Thu, 07 Jan 2021 18:08:32 GMT
last-modified: Thu, 07 Jan 2021 18:04:48 GMT
server: ECS (dab/4B67)
strict-transport-security: max-age=631138519
x-cache: 404-HIT
x-connection-hash: fc637f9c69b3313c25f29ff4c12e289a
x-content-type-options: nosniff
x-response-time: 13
x-tw-cdn: VZ
x-tw-cdn: VZ
content-length: 0

$ curl -I https://pbs.twimg.com/profile_banners/16348722/1355568199/1500x500
HTTP/2 200 
accept-ranges: bytes
access-control-allow-origin: *
access-control-expose-headers: Content-Length
age: 646
cache-control: max-age=604800, must-revalidate
content-type: image/jpeg
date: Thu, 07 Jan 2021 18:08:38 GMT
last-modified: Sat, 15 Dec 2012 10:41:19 GMT
server: ECS (dab/4AD4)
strict-transport-security: max-age=631138519
surrogate-key: profile_banners profile_banners/bucket/7 profile_banners/16348722
x-cache: HIT
x-connection-hash: ad3506228ce83c48e4704a9fb7832eda
x-content-type-options: nosniff
x-response-time: 240
x-tw-cdn: VZ
x-tw-cdn: VZ
content-length: 65602
```

Given that I suck at Python, I am not sure how to append that bit to the URL it fetches.

Oh wait, I think I got it...

https://github.com/robertoszek/pleroma-twitter-info-grabber/blob/28c1c7df57d8a37f8f361cb8639e9bad5a41bc9e/pleroma_bot/_pleroma.py#L179

I changed to:

```python
response = requests.get(self.profile_banner_url + '/1500x500', stream=True)
```

Again, I have no idea if this is the proper way to do it but it seems to work lol

**Comment by robertoszek** [comment]
Hmm interesting, yes, appending "/1500x500" works.
Please open an issue if you can and provide the Twitter user for which retrieving the banner is failing, I'll take a look at what the Twitter API response looks like.

Regarding the original issue, it's been merged and released on master. You can upgrade by running:
```console
pip install --upgrade pleroma-bot
```

**Comment by robertoszek** [comment]
Nevermind, I found the user and I was able to reproduce the issue. 
I pushed the fix to master and released it to PyPi as well. Same thing as before, you can get the latest version by running: 
```console
pip install --upgrade pleroma-bot
```
Thanks!

**Comment by jimmybrancaccio** [comment]
Awesome, thanks so much @robertoszek. I definitely do apologize for not creating a new issue for the profile banner size. I should know better than that!

**Comment by robertoszek** [comment]
No worries @jimmybrancaccio, it's all good 👍
When I wrote that code I was under the impression  that the user property ```profile_banner_url``` would always be enough to retrieve the banner image everytime, thanks to your post I went I took a more thorough look into the [Profile banners Twitter API page](https://developer.twitter.com/en/docs/twitter-api/v1/accounts-and-users/user-profile-images-and-banners) which cleared things up for me.
Don't hesitate to point out more issues if you ran into them and feel free to open as many as you need! 😉
