### ISSUE TITLE
Add Option To Ignore @ replies From Twitter

### ISSUE THREAD

**Issue by jimmybrancaccio** [robertoszek/pleroma-twitter-info-grabber#29]
Having an option to ignore @ replies from tweet would cut down on the amount of tweet to toots I am seeing. Generally 95% of the @ replies from Twitter aren't directed at me so I don't necessarily see any value in adding them to Pleroma/Mastodon. For example, brands do a lot of @ replies as they support users over Twitter.

I made some small changes to `_pleroma.py` which I believe will skip @ replies. However it doesn't factor in an actual option to enable or disable the functionality. I suppose it's a start though. Around line 79:

```python
    result = tweet_text.startswith('@')
    while not result:
        print (f'Tweet did not start with "@", processing...')
        if self.media_upload:
            for file in media_files:
```

Probably don't need the `print` statement but may be useful for debugging.

**Comment by robertoszek** [comment]
Agreed, this would a much welcomed quality of life improvement we could let the users choose to use.
However, I actually see this enhancement as including **replies** or not, not as including tweets which begin with '@' or not. I could write a new tweet mentioning someone without it being a reply neccesarily, I see the value of keeping that hypothetical "new" tweet when posting it to the Fediverse account.

Twitter's API has this field called ```referenced_tweets``` for each tweet which is a list of dicts. These dicts have the attribute ```type``` which can take the value ```replied_to```, if the tweet in question is a reply to another existing one.

This is how we currently identify retweets and filter them, we could do much the same for replies:
https://github.com/robertoszek/pleroma-twitter-info-grabber/blob/039ed7279240ed7d7146fac1a267cbc6030bce4e/pleroma_bot/_utils.py#L116-L125

**Comment by robertoszek** [comment]
Hi,
as I mentioned, I followed a similar approach to how we filtered RTs to acomplish the same thing with replies.
Here's the commit ce55a3c8fbff6df7bc7aff5d7fa1e9081c9bce5b

You can test it out with a staging release by running:
```console
pip install --index-url https://test.pypi.org/simple/ pleroma-bot --upgrade
```
Version number should be ```0.6.8```
These changes will be included on the next roll out to master.

**Comment by jimmybrancaccio** [comment]
> Twitter's API has this field called referenced_tweets for each tweet which is a list of dicts. These dicts have the attribute type which can take the value replied_to, if the tweet in question is a reply to another existing one.

@robertoszek That's definitely way better of an implementation. I hadn't dug too much into the Twitter API so I wasn't aware of `referenced_tweets`.

Any ETA on next master rollout? 😁

**Comment by robertoszek** [comment]
> Any ETA on next master rollout? 😁

Probably sometime next week, I'll need to receive some sort of confirmation that the unstaged changes solved your issues before pushing them though haha

I did my own testing but you never know, maybe I missed something particular to the instance you're pushing to.

**Comment by robertoszek** [comment]
Changes promoted to master. Let me know if you experience any issues with the fix implementation.
Cheers!
