### ISSUE TITLE
Support for polls

### ISSUE THREAD

**Issue by robertoszek** [robertoszek/pleroma-twitter-info-grabber#6]
Create a poll in Pleroma/Fediverse account with the same values as the original tweet.

**Comment by zoenglinghou** [comment]
Twitter API v1.1, which is used to get user timeline, does not seem to support poll metadata for individual devs. I would see if I can do it with v2

**Comment by zoenglinghou** [comment]
This is a minimum working example that I have got:

```bash
HEADER='Authorization: Bearer <token>'

# doesnt work on v1.1
# curl -H "$HEADER" -X GET 'https://api.twitter.com/1.1/statuses/user_timeline.json?screen_name=<userid>'

curl -H "$HEADER" -X GET 'https://api.twitter.com/2/tweets/search/recent?query=from:<userid>'
curl -H "$HEADER" -X GET 'https://api.twitter.com/2/tweets?ids=<tweetid>&expansions=attachments.poll_ids'
```

Returns:
```json
{"data":[{"id":"<tweetid>","text":"test poll"}],"meta":{"newest_id":"<newid>","oldest_id":"<oldid>","result_count":1}}
{"data":[{"attachments":{"poll_ids":["<pollid>"]},"id":"<pollid>","text":"test poll"}],"includes":{"polls":[{"id":"<pollid>","options":[{"position":1,"label":"option1","votes":0},{"position":2,"label":"option2","votes":0}]}]}}
```

**Comment by robertoszek** [comment]
Yeah, right now the only thing we're using v2 is for retrieving the pinned tweets (which also don't work with v1.1). The idea is to migrate everything to v2 in the long term.
Maybe is best to migrate the timeline to v2 first, then integrating the needed changes for supporting the poll functionality would be relativily easier.

```python
    def _get_pinned_tweet_id(self):
        """Retrieves the pinned tweet by the user

        :returns: ID of currently pinned tweet
        """
        url = self.twitter_base_url_v2 + '/users/by/username/' + self.twitter_username
        params = {"user.fields": "pinned_tweet_id", "expansions": "pinned_tweet_id", "tweet.fields": "entities"}
        response = requests.get(url, headers=self.header_twitter, params=params)
        try:
            data = json.loads(response.text)
            pinned_tweet = data['includes']['tweets'][0]
            pinned_tweet_id = pinned_tweet['id']
        except (JSONDecodeError, KeyError):
            pinned_tweet_id = None
            pass
        return pinned_tweet_id
```

**Comment by robertoszek** [comment]
I just pushed the changes needed for migrating to Twitter API v2:
[9137c2a](https://github.com/robertoszek/pleroma-twitter-info-grabber/commit/9137c2a6eb081088b0d4072c7921b32163039059)
We still fall back to v1.1 to download video attachments though 😓️ (is not supported on v2 yet). 

The important thing is that we retrieve everything else using v2, which contains all the poll entities and metadata needed for processing.

**Comment by zoenglinghou** [comment]
I just implemented polls in [this commit](3f3dc1e0907f83b52b159aff10ed2556d989b436).

However, in the haste of making a test twitter account, the program threw exceptions since there is no profile and banner image on twitter. I proceeds to fix it in the same commit (bad practice but I can't really test polling without fixing it)

There is also an exception in processing the pinned tweets that needs to be fixed.

**Comment by robertoszek** [comment]
> There is also an exception in processing the pinned tweets that needs to be fixed.

Dang it, I thought I fixed that on the develop branch with this commit: [d765f77](https://github.com/robertoszek/pleroma-twitter-info-grabber/commit/d765f77ce2aa3e501e40f5e33a7b6d18c25bb275). Could you provide me some info to help me reproduce it?

Good job with the polls! I'll try to find some time this week to verify it works as expected, at a glance it looks pretty good, thanks!

**Comment by zoenglinghou** [comment]
Oops, seems like I am not working on the most current branch somehow... That's my bad... I would test on your latest commit later.

**Comment by robertoszek** [comment]
Well, I just happened to have the time to test it out right now haha
So I went ahead and manually merged your changes into this repo's develop branch (there were some conflicts I needed to take care of anyway).

I had to make very minimal changes to make it work for tweets which don't have any attachments, fyi. [fb20f72](https://github.com/robertoszek/pleroma-twitter-info-grabber/commit/fb20f72fd96f32c11c0c5fdbefe73225bf9cdd5b)

Apart from that it's working wonderfully, thanks again! 

Let me know if the pinned tweet is still triggering an exception for you, I couldn't reproduce it yet.

**Comment by zoenglinghou** [comment]
Yeah, the pinned tweet is fixed. Thanks a lot for that!

The profile image url fix is not working for me for some reason tho. Somehow the API is returning a default image instead of having no `profile_image_url` key, but only working over `https`. `404` is returned when requesting the default profile image over `http` with this url: http://abs.twimg.com/sticky/default_profile_images/default_profile_400x400.png. The issue could be closed now and I would drop in a fix later.

**Comment by robertoszek** [comment]
Good to know the pinned tweets are working!
Hmm, that's very interesting behaviour for the API over http as opposed to https.
Closing this issue, feel free to open new ones as you see fit.
